### ISSUE TITLE
Possibility to opt out storing all entities in the "store" set

### ISSUE THREAD

**Issue by olederle** [arnelenero/simpler-state#19]
**Is your feature request related to a problem? Please describe.**
The resetAll function is very good in unit tests, to reset the state of all the entities. But storing all entities in the private "store" Set prevents a few usage scenarios, in which you need more control over the lifecycle of an entity. 

In our application we have a few services, for wich we would like to use an entity as backend. But it's possible that a new service is created and therefore a new entity as well. But the old entity instance is still referenced by the "store" Set.

Our app is a little bit bigger and has multiple sections. We also persist the state to local storage. So we could destroy the entities of a section, when the user moves to a different section. We can restore the state from local storage (for the case the user comes back to the section, which might not happen at all). But again the old entities would still be referenced by the private Set.

And in a last use case, I would like to use entity together with some state stored in the URL. This entity should just live as long as the user is on a specific page. I know when the user enters or leaving the page, and are able to hold a reference to the entity for this duration. 

**Describe the solution you'd like**
To be able to use entities for all our usage scenarios, we would need the possibility to prevent adding entities to the "store" Set. Sooner or later this would result in some memory issues, as the Set would continuously grow. Otherwise we get everything from this library we need.

![image](https://user-images.githubusercontent.com/11004213/152487935-f52f7595-3110-42ef-9175-5534fa0dcd86.png)

Is it possible to add a possibility to opt-out this behaviour for a production build?
* Some global configuration
* Conditional build statement
* public access to the Set or a function to clear it?

**Additional context**
So far the Set should not be needed for the functionality of the library, because there is also no access to it except the "resetAll" function. If you follow the documentation and store the entity globally, the reference to the entity exist anyway the whole time. And if you use an approach like sticky state, you have to store the entities by a key as well. So this should not change the behaviour of the library, because I think the resetAll function should only be used for testing purpose. Anyway I think currently you need to be aware of the "private" Set. Even if you do not reference an entity for the whole lifetime of the application, all entities will be referenced and never garbage collected. I know, in most cases this should not be an issue, as entities are "global" most of the time. But if you do some sort of sticky state, store the entities yourself and think, you can destroy all of that state at some time, currently that will not work very well.

**Comment by arnelenero** [comment]
Hi @olederle . Thank you very much for your detailed FR submission.

You raised a very valid point, particularly as it relates to scaling with the complexity of the app, i.e. more and more entities are instantiated. Since the "index" Set is only used for unit testing (`resetAll`), adding entities to this index set should only be done during test.

The solution that I have in mind right now is to forgo the adding to the set by default, and then providing a function to enable reset-all functionality in tests. 

Would this completely address your concern?

**Comment by olederle** [comment]
Your solution is even better. I wasn't thinking about that, but to enable it manually for tests seems to be the better approach. You can not forget to disable it in production mode then. And I think it should not be an issue to enable it for testing purpose, or that there is a risk to forget this if you need it.

And yes, this would completely address my concern.

**Comment by arnelenero** [comment]
I am marking this for implementation. It should be a fairly straightforward change. It would need a minor version bump, though, because it breaks existing tests that call `resetAll`.

**Comment by olederle** [comment]
Do you have any idea, when this might be implemented?

**Comment by arnelenero** [comment]
Aiming to release this within the coming week (before end of Feb).

**Comment by arnelenero** [comment]
Here is an excerpt from the updated documentation, explaining the changes in this release:

--- Excerpt from doc ---

Starting with version 1.1, simpler-state optimizes the lifecycle of the entities so that they are properly garbage collected. This is to support larger applications where entities can be dynamically created and destroyed on demand.

Historically, in order to support `resetAll`, the library adds every entity created by the app in a private global store. Due to the optimization mentioned above, the use of this store is now on an opt-in basis, considering that we would only need it for testing.

We will need to enable the store before we can invoke `resetAll`, otherwise it will throw an error. For this we can use the `enableStore` function. This function needs to be invoked once **before the entities are created**. In Jest, the easiest way to do this is to invoke `enableStore()` in a Jest setup JavaScript.

**setupTests.js**

```js
const { enableStore } = require('simpler-state')

enableStore()
```

If the project was created using Create React App, this setup file should be in the `src` folder and Jest would be pre-configured to look for it there. Otherwise, add this to the Jest config:

```json
{
  "setupFilesAfterEnv": ["./setupTests.js"]
}
```

This will ensure that the store is enabled before any of the modules creating the entities are loaded.

**Comment by arnelenero** [comment]
@olederle Version 1.1.0 has been released. Please evaluate when you get the chance. I am keeping this issue open for now.

**Comment by arnelenero** [comment]
Closing this as the feature has been implemented and tested.
