### ISSUE TITLE
Please review: useStickyState

### ISSUE THREAD

**Issue by philipmjohnson** [arnelenero/simpler-state#8]
After reading about Simpler State, I implemented a simple wrapper called "useStickyState" for my application. The idea is to provide a more-or-less drop-in replacement for the React useState() hook.  

I am wondering if the developers would mind taking a minute or two to look at my implementation to tell me if they see any issues with it:

https://github.com/radgrad/radgrad2/blob/master/app/imports/ui/utilities/StickyState.ts

Here's my initial documentation for our developers:

https://www.radgrad.org/docs/developers/patterns/sticky-state

Thanks for any suggestions!

**Comment by arnelenero** [comment]
> After reading about Simpler State, I implemented a simple wrapper called "useStickyState" for my application. The idea is to provide a more-or-less drop-in replacement for the React useState() hook.
> 
> I am wondering if the developers would mind taking a minute or two to look at my implementation to tell me if they see any issues with it:
> 
> https://github.com/radgrad/radgrad2/blob/master/app/imports/ui/utilities/StickyState.ts
> 
> Here's my initial documentation for our developers:
> 
> https://www.radgrad.org/docs/developers/patterns/sticky-state
> 
> Thanks for any suggestions!

Hi,

I really like this pattern of "sticky state", and in fact I do use this pattern in some of my work projects.

Your source code looks good.  I just have a couple of questions/comments:

1.  For this part of the code:

```js
  if (entities[name]) {
    const { savedEntity, savedSetter } = entities[name];
    return [savedEntity.use(), savedSetter];
  }
```
wouldn't it be simpler if you just return something like this?
```js
  const namedEntity = entities[name];
  if (namedEntity) return [namedEntity.use(), namedEntity.set]
```
I propose this because it looks like you are using the setter as-is, as indicated in this line:
```js
  const newEntitySetter = (newValue) => newEntity.set(newValue);
```

2.  If you agree with my proposed simplification above, the rest of the code could looks as short as this:
```js
  // Otherwise create a new entity
  const newEntity = entity(initialValue);
  entities[name] = newEntity;
  return [newEntity.use(), newEntity.set];
```

Do let me know if I missed something important here.  I typed this review on a Sunday so my brain might not be working like usual on a weekday.  🤣

**Comment by philipmjohnson** [comment]
Thanks for the quick reply!  Great suggestions.

Sure, feel free to use this code/idea any way you like. Thanks for providing Simpler State to the community.
